namespace UFBX.Interop
{
    public enum ApertureMode
    {
        UFBX_APERTURE_MODE_HORIZONTAL_AND_VERTICAL,
        UFBX_APERTURE_MODE_HORIZONTAL,
        UFBX_APERTURE_MODE_VERTICAL,
        UFBX_APERTURE_MODE_FOCAL_LENGTH,
    }
}
