namespace UFBX.Interop
{
    public enum ApertureFormat
    {
        UFBX_APERTURE_FORMAT_CUSTOM,
        UFBX_APERTURE_FORMAT_16MM_THEATRICAL,
        UFBX_APERTURE_FORMAT_SUPER_16MM,
        UFBX_APERTURE_FORMAT_35MM_ACADEMY,
        UFBX_APERTURE_FORMAT_35MM_TV_PROJECTION,
        UFBX_APERTURE_FORMAT_35MM_FULL_APERTURE,
        UFBX_APERTURE_FORMAT_35MM_185_PROJECTION,
        UFBX_APERTURE_FORMAT_35MM_ANAMORPHIC,
        UFBX_APERTURE_FORMAT_70MM_PROJECTION,
        UFBX_APERTURE_FORMAT_VISTAVISION,
        UFBX_APERTURE_FORMAT_DYNAVISION,
        UFBX_APERTURE_FORMAT_IMAX,
    }
}
