namespace UFBX.Interop
{
    public enum ConstraintType
    {
        UFBX_CONSTRAINT_UNKNOWN,
        UFBX_CONSTRAINT_AIM,
        UFBX_CONSTRAINT_PARENT,
        UFBX_CONSTRAINT_POSITION,
        UFBX_CONSTRAINT_ROTATION,
        UFBX_CONSTRAINT_SCALE,
        UFBX_CONSTRAINT_SINGLE_CHAIN_IK,
    }
}
