namespace UFBX.Interop
{
    public enum CoordinateAxis
    {
        UFBX_COORDINATE_AXIS_POSITIVE_X,
        UFBX_COORDINATE_AXIS_NEGATIVE_X,
        UFBX_COORDINATE_AXIS_POSITIVE_Y,
        UFBX_COORDINATE_AXIS_NEGATIVE_Y,
        UFBX_COORDINATE_AXIS_POSITIVE_Z,
        UFBX_COORDINATE_AXIS_NEGATIVE_Z,
        UFBX_COORDINATE_AXIS_UNKNOWN,
    }
}
