namespace UFBX.Interop
{
    public enum ErrorType
    {
        UFBX_ERROR_NONE,
        UFBX_ERROR_UNKNOWN,
        UFBX_ERROR_FILE_NOT_FOUND,
        UFBX_ERROR_OUT_OF_MEMORY,
        UFBX_ERROR_MEMORY_LIMIT,
        UFBX_ERROR_ALLOCATION_LIMIT,
        UFBX_ERROR_TRUNCATED_FILE,
        UFBX_ERROR_IO,
        UFBX_ERROR_CANCELLED,
        UFBX_ERROR_UNSUPPORTED_VERSION,
        UFBX_ERROR_NOT_FBX,
        UFBX_ERROR_UNINITIALIZED_OPTIONS,
    }
}
