namespace UFBX.Interop
{
    public enum Exporter
    {
        UFBX_EXPORTER_UNKNOWN,
        UFBX_EXPORTER_FBX_SDK,
        UFBX_EXPORTER_BLENDER_BINARY,
        UFBX_EXPORTER_BLENDER_ASCII,
        UFBX_EXPORTER_MOTION_BUILDER,
        UFBX_EXPORTER_BC_UNITY_EXPORTER,
    }
}
