namespace UFBX.Interop
{
    public enum MaterialFbxMap
    {
        UFBX_MATERIAL_FBX_DIFFUSE_FACTOR,
        UFBX_MATERIAL_FBX_DIFFUSE_COLOR,
        UFBX_MATERIAL_FBX_SPECULAR_FACTOR,
        UFBX_MATERIAL_FBX_SPECULAR_COLOR,
        UFBX_MATERIAL_FBX_SPECULAR_EXPONENT,
        UFBX_MATERIAL_FBX_REFLECTION_FACTOR,
        UFBX_MATERIAL_FBX_REFLECTION_COLOR,
        UFBX_MATERIAL_FBX_TRANSPARENCY_FACTOR,
        UFBX_MATERIAL_FBX_TRANSPARENCY_COLOR,
        UFBX_MATERIAL_FBX_EMISSION_FACTOR,
        UFBX_MATERIAL_FBX_EMISSION_COLOR,
        UFBX_MATERIAL_FBX_AMBIENT_FACTOR,
        UFBX_MATERIAL_FBX_AMBIENT_COLOR,
        UFBX_MATERIAL_FBX_NORMAL_MAP,
        UFBX_MATERIAL_FBX_BUMP,
        UFBX_MATERIAL_FBX_BUMP_FACTOR,
        UFBX_MATERIAL_FBX_DISPLACEMENT_FACTOR,
        UFBX_MATERIAL_FBX_DISPLACEMENT,
        UFBX_MATERIAL_FBX_VECTOR_DISPLACEMENT_FACTOR,
        UFBX_MATERIAL_FBX_VECTOR_DISPLACEMENT,
        UFBX_NUM_MATERIAL_FBX_MAPS,
    }
}
