namespace UFBX.Interop
{
    public enum PropFlags
    {
        UFBX_PROP_FLAG_ANIMATABLE = 0x1,
        UFBX_PROP_FLAG_USER_DEFINED = 0x2,
        UFBX_PROP_FLAG_HIDDEN = 0x4,
        UFBX_PROP_FLAG_LOCK_X = 0x10,
        UFBX_PROP_FLAG_LOCK_Y = 0x20,
        UFBX_PROP_FLAG_LOCK_Z = 0x40,
        UFBX_PROP_FLAG_LOCK_W = 0x80,
        UFBX_PROP_FLAG_MUTE_X = 0x100,
        UFBX_PROP_FLAG_MUTE_Y = 0x200,
        UFBX_PROP_FLAG_MUTE_Z = 0x400,
        UFBX_PROP_FLAG_MUTE_W = 0x800,
        UFBX_PROP_FLAG_SYNTHETIC = 0x1000,
        UFBX_PROP_FLAG_ANIMATED = 0x2000,
        UFBX_PROP_FLAG_NOT_FOUND = 0x4000,
        UFBX_PROP_FLAG_CONNECTED = 0x8000,
        UFBX_PROP_FLAG_NO_VALUE = 0x10000,
        UFBX_PROP_FLAG_OVERRIDDEN = 0x20000,
    }
}
