namespace UFBX.Interop
{
    public enum SubdivisionBoundary
    {
        UFBX_SUBDIVISION_BOUNDARY_DEFAULT,
        UFBX_SUBDIVISION_BOUNDARY_LEGACY,
        UFBX_SUBDIVISION_BOUNDARY_SHARP_NONE,
        UFBX_SUBDIVISION_BOUNDARY_SHARP_CORNERS,
        UFBX_SUBDIVISION_BOUNDARY_SHARP_BOUNDARY,
        UFBX_SUBDIVISION_BOUNDARY_SHARP_INTERIOR,
    }
}
